addons:
  firefox: "83.0"

matrix:
  include:
    - language: node_js
      node_js:
        - 14
      install:
        - cd wasmaudioworklet
        - npm install
      script: "npm run test"
      name: "Chrome headless"
    - dist: xenial
      services:
        - xvfb
      node_js:
        - 14
      install:
        - cd wasmaudioworklet
        - npm install
      script: "npm run test-firefox"
      name: "Firefox xvfb"
    - language: node_js
      node_js:
        - 14
      install:
        - cd wasmaudioworklet/synth1
        - npm install
      script: "npm run test:ci"
      name: "As-pect AssemblyScript"