// E.PIANO 1 — Yamaha DX7 patch as a self-contained Faust instrument
//
//   ROM file:   ROM1A.syx
//   Patch:      #11 "E.PIANO 1"
//   Algorithm:  5
//
// Every patch parameter is a constant in this file. The only MIDI-facing
// controls are freq, gate and gain, so the song carries no NRPN patch data.
// Drop it into a project as faust/epiano.dsp and import the generated
// `Epiano` voice class in synth.ts. To automate a parameter from the song,
// replace its constant with an hslider of the same range.
//
// Generated by examples/dx7/parse-rom.js. Regenerate with:
//   node parse-rom.js ROM1A.syx 11 --dsp --name epiano > dsp/epiano.dsp
//
// Values are in the DX7's own units, as dx.operator expects them. The
// operator routing is dx7_algo(5) from Faust's dx7.lib (David Braun, 2.0.0);
// op(i, 0) marks an operator with no modulator input.

import("stdfaust.lib");

freq = hslider("freq", 440, 20, 20000, 0.01);
gate = button("gate");
gain = hslider("gain", 0.5, 0, 1, 0.01);

// ---- Global ----------------------------------------------------------------
feedback        =   6;  // 0-7, operator self-modulation depth
transpose       =   0;  // semitones, -24..24 (ROM stores 0-48, 24 = 0)
oscKeySync      =   0;  // 0/1, restart oscillator phase on key-on
pitchEgR1       =  94;  // pitch EG rates 0-99
pitchEgR2       =  67;
pitchEgR3       =  95;
pitchEgR4       =  60;
pitchEgL1       =  50;  // pitch EG levels 0-99 (50 = no pitch change)
pitchEgL2       =  50;
pitchEgL3       =  50;
pitchEgL4       =  50;
lfoWave         =   4;  // 0=Triangle 1=Saw Down 2=Saw Up 3=Square 4=Sine 5=S&H
lfoSpeed        =  34;  // 0-99
lfoDelay        =  33;  // 0-99
lfoPMD          =   0;  // LFO pitch modulation depth 0-99
lfoAMD          =   0;  // LFO amplitude modulation depth 0-99
lfoSync         =   0;  // 0/1, restart LFO on key-on
lfoPitchModSens =   3;  // 0-7

// ---- Per operator ------------------------------------------------------------
//                                OP1  OP2  OP3  OP4  OP5  OP6
freqMode(i)         = ba.take(i+1, (  0,   0,   0,   0,   0,   0));  // 0 = ratio of the note, 1 = fixed frequency
freqCoarse(i)       = ba.take(i+1, (  1,  14,   1,   1,   1,   1));  // ratio 0-31 (0 = 0.5); fixed: 1/10/100/1000 Hz
freqFine(i)         = ba.take(i+1, (  0,   0,   0,   0,   0,   0));  // 0-99
detune(i)           = ba.take(i+1, (  3,   0,   0,   0,  -7,   7));  // -7..7 (ROM stores 0-14, 7 = center)
outLevel(i)         = ba.take(i+1, ( 99,  58,  99,  89,  99,  79));  // output level 0-99
egR1(i)             = ba.take(i+1, ( 96,  95,  95,  95,  95,  95));  // amp EG rates 0-99
egR2(i)             = ba.take(i+1, ( 25,  50,  20,  29,  20,  29));
egR3(i)             = ba.take(i+1, ( 25,  35,  20,  20,  20,  20));
egR4(i)             = ba.take(i+1, ( 67,  78,  50,  50,  50,  50));
egL1(i)             = ba.take(i+1, ( 99,  99,  99,  99,  99,  99));  // amp EG levels 0-99
egL2(i)             = ba.take(i+1, ( 75,  75,  95,  95,  95,  95));
egL3(i)             = ba.take(i+1, (  0,   0,   0,   0,   0,   0));
egL4(i)             = ba.take(i+1, (  0,   0,   0,   0,   0,   0));
keyVelSens(i)       = ba.take(i+1, (  2,   7,   2,   6,   0,   6));  // key velocity sensitivity 0-7
ampModSens(i)       = ba.take(i+1, (  0,   0,   0,   0,   0,   0));  // amplitude modulation sensitivity 0-3
rateScale(i)        = ba.take(i+1, (  3,   3,   3,   3,   3,   3));  // EG rate scaling 0-7
breakpoint(i)       = ba.take(i+1, (  0,   0,   0,   0,   0,  41));  // keyboard level scaling breakpoint 0-99 (39 = C3)
breakpointLDepth(i) = ba.take(i+1, (  0,   0,   0,   0,   0,   0));  // level scaling depth left of breakpoint 0-99
breakpointRDepth(i) = ba.take(i+1, (  0,   0,   0,   0,   0,  19));  // level scaling depth right of breakpoint 0-99
breakpointLCurve(i) = ba.take(i+1, (  0,   0,   0,   0,   0,   0));  // curves 0-3: -LIN -EXP +EXP +LIN
breakpointRCurve(i) = ba.take(i+1, (  0,   0,   0,   0,   0,   0));

// dx.operator argument order is fixed by operator.lib — do not reorder.
op(i, phase_mod) = dx.operator(
    freqMode(i), freqCoarse(i), freqFine(i), detune(i), outLevel(i),
    egR1(i), egR2(i), egR3(i), egR4(i),
    egL1(i), egL2(i), egL3(i), egL4(i),
    keyVelSens(i), ampModSens(i), rateScale(i),
    breakpoint(i), breakpointLDepth(i), breakpointRDepth(i), breakpointLCurve(i), breakpointRCurve(i),
    lfoWave, lfoSpeed, lfoDelay, lfoPMD, lfoAMD, lfoSync, lfoPitchModSens,
    oscKeySync,
    pitchEgR1, pitchEgR2, pitchEgR3, pitchEgR4,
    pitchEgL1, pitchEgL2, pitchEgL3, pitchEgL4,
    transpose, phase_mod, freq, gain, gate
);

feedbackAmp = dx.fdbkscalef(feedback);

// Algorithm 5
process = (op2 : op1),(op4 : op3),(op6~*(feedbackAmp) : op5) :> _ <: _,_
with {
    op1 = op(0);
    op2 = op(1, 0);
    op3 = op(2);
    op4 = op(3, 0);
    op5 = op(4);
    op6 = op(5);
};
